general:
  seed: 0
  device: 0
  logs_tensorboard: ./results/test_v2/
  ascad_database_file: ./datasets/ASCAD_dataset/ASCAD_dataset/ASCAD.h5

dataloader:
  scaling: feature_scaling_m1_1
  batch_size: 50
  num_workers: 0
  shuffle: True

test_dataloader:
  scaling: feature_scaling_m1_1
  batch_size: 10000
  num_workers: 0
  shuffle: False

train:
  criterion: Categorical Cross Entropy Loss
  optimizer: Adam
  epochs: 50
  lr: 5e-3
  momentum: 0.9


