general:
  seed: 0
  device: 0
  logs_tensorboard: ./results/test_v2/
  ascad_database_file: ./datasets/ASCAD_dataset/ASCAD_dataset/ASCAD.h5

dataloader:
  scaling: feature_scaling_m1_1
  batch_size: 4
  num_workers: 0
  shuffle: True

train:
  criterion: CrossEntropyLoss
  optimizer: Adam
  epochs: 5
  lr: 0.001
  momentum: 0.9


